name: confront-frontend

services:
  front-end:
    build:
      context: ../../front-app
      dockerfile: Dockerfile
    image: nextjs-standalone-image
    environment:
      NODE_ENV: production
      PORT: "${PORT}"
    ports:
      - "3000:${PORT}"
    container_name: ${COMPOSE_PROJECT_NAME}-front
    restart: always